# Generated by Django 4.1 on 2022-09-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='NoCol', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='noimage', upload_to='C:\\\\Users\\\\vs344\\OneDrive\\\\Pictures\\\\Camera Roll'),
        ),
    ]
